# Generated by Django 5.0.3 on 2024-03-30 11:04

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HoneypotService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service_type",
                    models.CharField(
                        choices=[("ssh", "SSH"), ("http", "HTTP")], max_length=50
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
            ],
        ),
    ]
