# Generated by Django 5.0.3 on 2024-03-30 14:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opencanary_configurator", "0002_rename_is_active_honeypotservice_is_enabled"),
    ]

    operations = [
        migrations.CreateModel(
            name="OpenCanaryLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dst_host", models.CharField(max_length=100)),
                ("dst_port", models.IntegerField()),
                ("local_time", models.DateTimeField()),
                ("logdata", models.JSONField()),
                ("logtype", models.IntegerField()),
                ("node_id", models.CharField(max_length=100)),
                ("src_host", models.CharField(max_length=100)),
                ("src_port", models.IntegerField()),
                ("utc_time", models.DateTimeField()),
            ],
        ),
    ]
