# Generated by Django 5.0.3 on 2024-03-30 15:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opencanary_configurator", "0003_opencanarylog"),
    ]

    operations = [
        migrations.AddField(
            model_name="opencanarylog",
            name="local_time_adjusted",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
