# Generated by Django 5.0.3 on 2024-03-30 15:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("opencanary_configurator", "0005_httplog_sshlog_delete_opencanarylog"),
    ]

    operations = [
        migrations.DeleteModel(
            name="HttpLog",
        ),
        migrations.DeleteModel(
            name="SshLog",
        ),
    ]
