# Generated by Django 5.0.3 on 2024-03-31 18:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opencanary_configurator", "0006_delete_httplog_delete_sshlog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="honeypotservice",
            name="service_type",
            field=models.CharField(
                choices=[("http", "HTTP"), ("https", "HTTPS")], max_length=50
            ),
        ),
    ]
