# Generated by Django 5.0.3 on 2024-04-01 19:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="loginattempt",
            name="timestamp",
        ),
        migrations.AddField(
            model_name="loginattempt",
            name="username",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="loginattempt",
            name="ip_address",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
