# Generated by Django 5.0.3 on 2024-04-01 20:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_remove_loginattempt_timestamp_loginattempt_username_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="loginattempt",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
