# Generated by Django 5.0.3 on 2024-04-01 20:16

import django.utils.timezone
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0003_loginattempt_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="loginattempt",
            name="country",
            field=django_countries.fields.CountryField(
                blank=True, max_length=2, null=True
            ),
        ),
        migrations.AddField(
            model_name="loginattempt",
            name="path_requested",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="loginattempt",
            name="success",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="loginattempt",
            name="user_agent",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="loginattempt",
            name="timestamp",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
