# Generated by Django 5.0.3 on 2024-04-02 15:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0005_alter_loginattempt_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="loginattempt",
            name="username",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
