# Generated by Django 5.0.3 on 2024-04-02 15:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0006_loginattempt_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="loginattempt",
            name="ipv4",
        ),
        migrations.RemoveField(
            model_name="loginattempt",
            name="ipv6",
        ),
        migrations.AddField(
            model_name="loginattempt",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
