# Generated by Django 5.0.3 on 2024-04-02 16:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0008_remove_loginattempt_ip_address_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserLoginAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=150)),
                ("password", models.CharField(max_length=128)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField()),
            ],
            options={
                "verbose_name_plural": "Login Attempts",
            },
        ),
        migrations.DeleteModel(
            name="LoginAttempt",
        ),
    ]
