# Generated by Django 5.0.3 on 2024-04-02 16:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0010_loginattempt_delete_userloginattempt"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="loginattempt",
            name="username",
        ),
    ]
