# Generated by Django 5.0.3 on 2024-04-02 16:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0011_remove_loginattempt_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="loginattempt",
            name="ip_address",
        ),
        migrations.AddField(
            model_name="loginattempt",
            name="ipv4_address",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="loginattempt",
            name="ipv6_address",
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
