# Generated by Django 5.0.3 on 2024-04-02 16:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0012_remove_loginattempt_ip_address_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="loginattempt",
            name="ipv4_address",
        ),
        migrations.RemoveField(
            model_name="loginattempt",
            name="ipv6_address",
        ),
        migrations.AddField(
            model_name="loginattempt",
            name="ip_address",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
