# Generated by Django 5.0.3 on 2024-04-02 17:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0013_remove_loginattempt_ipv4_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="loginattempt",
            name="location",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="loginattempt",
            name="ip_address",
            field=models.CharField(max_length=45),
        ),
    ]
