# Generated by Django 5.0.3 on 2024-04-02 17:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0014_loginattempt_location_alter_loginattempt_ip_address"),
    ]

    operations = [
        migrations.RenameField(
            model_name="loginattempt",
            old_name="location",
            new_name="browser",
        ),
        migrations.AddField(
            model_name="loginattempt",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="loginattempt",
            name="country",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="loginattempt",
            name="isp",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="loginattempt",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=15, max_digits=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="loginattempt",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=15, max_digits=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="loginattempt",
            name="platform",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="loginattempt",
            name="referring_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="loginattempt",
            name="state",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="loginattempt",
            name="user_agent",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
