# Generated by Django 5.0.3 on 2024-04-02 17:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0015_rename_location_loginattempt_browser_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="loginattempt",
            name="region",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="loginattempt",
            name="timezone",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
