# Generated by Django 5.0.3 on 2024-04-02 20:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0017_loginattempt_is_vpn"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="loginattempt",
            name="is_vpn",
        ),
    ]
