# Generated by Django 5.0.3 on 2024-04-02 21:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0018_remove_loginattempt_is_vpn"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loginattempt",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=15, max_digits=30, null=True
            ),
        ),
        migrations.AlterField(
            model_name="loginattempt",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=15, max_digits=30, null=True
            ),
        ),
    ]
