# Generated by Django 5.0.3 on 2024-04-03 06:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0020_loginattempt_vpn"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="loginattempt",
            name="vpn",
        ),
    ]
