# Generated by Django 5.0.3 on 2024-04-03 07:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0021_remove_loginattempt_vpn"),
    ]

    operations = [
        migrations.AddField(
            model_name="loginattempt",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="loginattempt",
            name="name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="loginattempt",
            name="passphrase",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
