# Generated by Django 5.0.3 on 2024-04-03 07:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0022_loginattempt_email_loginattempt_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loginattempt",
            name="name",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name="loginattempt",
            name="passphrase",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
