# Generated by Django 5.0.3 on 2024-04-03 07:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0023_alter_loginattempt_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="loginattempt",
            name="request_type",
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
